source 'http://rubygems.org'

gem 'kramdown'
gem 'commander'
gem 'shell-executer'
gem 'sass'
gem 'wicked_pdf'
gem 'activesupport'
gem 'stamp'
gem 'selenium-webdriver'
gem 'pdfcrowd'
gem 'listen'
gem 'rb-fsevent', '~> 0.9.1'
gem 'aws-sdk'

gem 'paint'
gem 'formatador'
